        date_format = idx.strftime("%Y%m%d")

        ic_grid = {}
        for hp in hps:
            path = BackTesting.add_hp_2_prediction_path(hp, self.prediction_path)
            ic_df = pd.read_csv(os.path.join(path, str(idx.year), str(idx.month).zfill(2), f"{date_format}_ic.csv"), index_col=0)
            ic_grid[tuple(hp.values())] = ic_df.squeeze()

        opt_hp = max(ic_grid, key=ic_grid.get)

        opt_hp_dict = dict(zip(hp.keys(), opt_hp))
        opt_hp_path = BackTesting.add_hp_2_prediction_path(opt_hp_dict, self.prediction_path)
        opt_hp_path = os.path.join(opt_hp_path, str(idx.year), str(idx.month).zfill(2))

        _logger.info(f"Extract optimal prediction from {opt_hp_path}.")
        test_data = pd.read_csv(os.path.join(opt_hp_path, f"{date_format}_test_data.csv"), index_col=0)
        opt_pred = pd.read_csv(os.path.join(opt_hp_path, f"{date_format}_preds.csv"), index_col=0)
        opt_coef = pd.read_csv(os.path.join(opt_hp_path, f"{date_format}_coef.csv"), index_col=0)
        opt_z0 = pd.read_csv(os.path.join(opt_hp_path, f"{date_format}_z0.csv"), index_col=0)
        opt_M = pd.read_csv(os.path.join(opt_hp_path, f"{date_format}_M.csv"), index_col=0)
        opt_N = pd.read_csv(os.path.join(opt_hp_path, f"{date_format}_N.csv"), index_col=0)
        opt_U = pd.read_csv(os.path.join(opt_hp_path, f"{date_format}_U.csv"), index_col=0)
        opt_Q = pd.read_csv(os.path.join(opt_hp_path, f"{date_format}_Q.csv"), index_col=0)
        scale = pd.read_csv(os.path.join(opt_hp_path, f"{date_format}_scale.csv"), index_col=0)

        # load optimal estimation
        matrix_path = os.path.join(self.model_selection_path, str(idx.year), str(idx.month).zfill(2), str(idx.day).zfill(2))
        Path(matrix_path).mkdir(parents=True, exist_ok=True)

        opt_coef.to_csv(os.path.join(matrix_path, f"{date_format}.coef.csv"))
        opt_z0.to_csv(os.path.join(matrix_path, f"{date_format}.z0.csv"))
        opt_M.to_csv(os.path.join(matrix_path, f"{date_format}.M.csv"))
        opt_N.to_csv(os.path.join(matrix_path, f"{date_format}.N.csv"))
        opt_U.to_csv(os.path.join(matrix_path, f"{date_format}.U.csv"))
        opt_Q.to_csv(os.path.join(matrix_path, f"{date_format}.Q.csv"))
        scale.to_csv(os.path.join(matrix_path, f"{date_format}.scale.csv"))
        opt_pred.to_csv(os.path.join(matrix_path, f"{date_format}.preds.csv"))  # the prediction generated by selected
        test_data.to_csv(os.path.join(matrix_path, f"{date_format}.scaled_ret.csv"))
        return idx, opt_pred, opt_hp, opt_coef, opt_z0, opt_M, opt_N, opt_U, opt_Q, scale, test_data

    def select_model(self):
        _logger.info("Run model selection.")
        hps = extract_hp(self.cfg.hp)

        # extract idx using first set of hp
        indices = extract_idx(hps[0], self.prediction_path)

        # parallel computing for each time index we do model selection
        result = Parallel(n_jobs=self.njobs)(delayed(self.pick_prediction)(idx, hps) for idx in indices)

        # debug
        # result = []
        # for idx in tqdm(indices):
        #     res = self.pick_prediction(idx)
        #     result.append(res)

        preds_df = pd.concat([x[1] for x in result], axis=0)
        models_df = get_model_path(result)

        _logger.info(f"Save {self.symbol} predictions and selected models.")

        preds_df.to_csv(os.path.join(self.model_selection_path, "predictions.csv"))
        models_df.to_csv(os.path.join(self.model_selection_path, "models.csv"))

    @staticmethod
    def prepare_miso(df: pd.DataFrame, universe: List, symbol: str):
        if df.columns[0] == "WEIGHTED":  # non-overlapping data
            data = df.pivot_table(values="WEIGHTED", index="DATETIME", columns="level_0")
            data["Target"] = data[symbol]
            ext_columns = ["Target"] + universe
            data = data[ext_columns]
        else:
            target = df.loc[(slice(None), symbol), "Target"]
            target = target.droplevel("level_0")
            input_df = []
            for sym in universe:
                input_tmp = df.loc[(slice(None), sym), ["Input"]].droplevel("level_0")
                input_df.append(input_tmp)
            input_df = pd.concat(input_df, axis=1)
            col_name = ["_".join([x[0], str(x[1])]) for x in list(zip(["Input"] * len(universe), (universe)))]
            data = pd.concat([target, input_df], axis=1)
            data.columns = ["Target"] + list(col_name)
        return data

    @timer_func
    def run(self):
        _logger.info(f"Running estimation for {self.symbol}.")
        if self.generate_data:
            df = self.get_data()
        else:
            df = self.load_data()

        if self.system == "SISO":
            df = df.loc[self.cfg.start_date : self.cfg.end_date]
        elif self.system == "MISO":
            df = df.loc[self.cfg.start_date :]
            df = BackTesting.prepare_miso(df, self.universe, self.symbol)
            df = df.ffill()
        elif self.system == "MIMO":
            df = df.loc[self.cfg.start_date : self.cfg.end_date, :]

        if self.mode == "gen_prediction":
            self.gen_predictions(df)
        elif self.mode == "debug":
            self.debug(df)
        else:
            raise ValueError("Mode doesnt exist.")

        self.select_model()

    def preds_2_position(
        self,
        mu: pd.DataFrame,
        B: np.ndarray,
        D: np.ndarray,
        C: np.ndarray,
        sod: np.ndarray,
        trdub: np.ndarray,
        trdlb: np.ndarray,
        posub: np.ndarray,
        poslb: np.ndarray,
        linear_cost: np.ndarray,
        S: np.ndarray,
        h1: np.ndarray,
        h2: np.ndarray,
        tau1: float,
        tau2: float,
        target_risk: float,
    ):
        """
        From predictions to positions
        """
        positions = {}

        Sigma = B.dot(C).dot(B.T) + D

        for r in mu.iterrows():
            pred = r[1].values.reshape(-1, 1)
            lambd = calc_lambd(B, D, pred, target_risk)

            pos, _, _ = mv_opt_with_factor_risk_beta_neutral(
                pred, B, D, C, linear_cost, S, sod, lambd, tau1, tau2, trdub, trdlb, posub, poslb, fexpub=h1, fexplb=h2
            )
            if np.isnan(pos).any():
                print("invalid solution")
                pos = np.zeros(sod.shape)

            pos_debug = closed_form_mv(pred, Sigma, lambd)

            positions[r[0]] = pos.ravel()
            # positions[r[0]] = pos_debug.ravel()
            sod = pos.copy()
        pos_df = pd.DataFrame.from_dict(positions, orient="index")
        return pos_df

    def preds_2_position_simple(
        self, mu: pd.DataFrame, B: np.ndarray, D: np.ndarray, C: np.ndarray, sod: np.ndarray, mvo_object: MVOWithFactorRisk
    ):
        """
        From predictions to positions
        """
        positions = {}
        fexposures = {}
        for r in mu.iterrows():
            pred = r[1].values.reshape(-1, 1)
            pos, fexp = mvo_object.fit(pred, sod, B, D, C)
            if np.isnan(pos).any():
                print("invalid solution")
                pos = np.zeros(sod.shape)
            positions[r[0]] = pos.ravel()
            fexposures[r[0]] = fexp.ravel()
            sod = pos.copy()
        pos_df = pd.DataFrame.from_dict(positions, orient="index")
        fexp_df = pd.DataFrame.from_dict(fexposures, orient="index")
        return pos_df, fexp_df

    def preds_2_position_with_cost(
        self, mu: pd.DataFrame, c: pd.DataFrame, B: np.ndarray, D: np.ndarray, C: np.ndarray, sod: np.ndarray, mvo_object: MVOWithFactorRisk
    ):
        """
        From predictions to positions
        """
        positions = {}
        fexposures = {}

        for i in range(mu.shape[0]):
            pred = mu.iloc[i].values.reshape(-1, 1)
            cost = c.iloc[i].values.reshape(-1, 1)
            mvo_object.c = cost
            pos, fexp = mvo_object.fit(pred, sod, B, D, C)
            if np.isnan(pos).any():
                import pdb

                pdb.set_trace()
                print("invalid solution")
                pos = np.zeros(sod.shape)
            positions[mu.iloc[i].name] = pos.ravel()
            fexposures[mu.iloc[i].name] = fexp.ravel()
            sod = pos.copy()
        pos_df = pd.DataFrame.from_dict(positions, orient="index")
        fexp_df = pd.DataFrame.from_dict(fexposures, orient="index")
        return pos_df, fexp_df

    @timer_func
    def portfolio_selection(self):
        # load price data
        date = datetime.datetime.strptime(self.cfg.end_date, "%Y-%m-%d")
        date_format = date.strftime("%Y%m%d")

        price_path_ = os.path.join(self.price_path, str(date.year), str(date.month).zfill(2))
        minute_price = pd.read_csv(os.path.join(price_path_, f"{date_format}.minute_price.csv"), index_col=0)
        minute_price.index = pd.to_datetime(minute_price.index)

        daily_price = minute_price.groupby(pd.Grouper(freq="1D")).last()
        daily_price = daily_price[(daily_price > 0).all(axis=1)]
        daily_rets = np.log(daily_price).diff().iloc[1:]

        # port setting
        sod = np.zeros((minute_price.shape[1], 1))

        # load predictions
        preds = []
        for u in self.universe:
            prediction_path = os.path.join(self.cfg.output_prefix, self.system, self.strats_name, "prediction", u)
            pred_df = pd.read_csv(os.path.join(prediction_path, "predictions.csv"), index_col=0)
            preds.append(pred_df)

        preds_df = pd.concat(preds, axis=1)
        preds_df.columns = self.universe
        preds_df.index = pd.to_datetime(preds_df.index)

        # load cost
        cost_path = "/ccny5/dat/strat/sft/yu/dp/rth_cc_data78_1min/{sym}/20230601"  # temporary
        costs = []

        for u in self.universe:
            cost_path_ = os.path.join(cost_path.format(sym=u), f"{u}_20230601_spread.csv")
            cost_df = pd.read_csv(cost_path_, index_col=0)
            costs.append(cost_df)
        costs_df = pd.concat(costs, axis=1)
        costs_df.columns = self.universe
        costs_df.index = pd.to_datetime(costs_df.index)
        costs_df = costs_df.ffill()

        # load optimizer
        port_inst = init_instance_by_config(self.cfg.port_cfg)

        num_days = len(daily_rets)
        all_positions = []
        all_fexps = []
        for i in tqdm(range(self.beta_window, num_days + 1)):
            df = daily_rets.iloc[:i]
            date_idx = df.index[-1].date()
            pre_idx = df.index[-2].date()
            date_format = date_idx.strftime("%Y%m%d")

            # load beta
            beta_path = os.path.join(self.price_path, str(date_idx.year), str(date_idx.month).zfill(2))
            beta = pd.read_csv(os.path.join(beta_path, f"{date_format}.beta.csv"), index_col=0)
            B = beta.loc[str(pre_idx)].values.reshape(-1, 1)

            idx = df.mean(axis=1)
            C = np.eye(1) * idx.var()

            # calculate residuals
            _, res = calc_residuals(df.loc[: str(pre_idx)], B)
            D = np.cov(res.T)
            od_mu = preds_df.loc[str(date_idx)]  # one day predictions
            od_cost = costs_df.loc[str(date_idx)]

            # fix cost
            # fixed_cost = np.tile([1e-4, 0.5e-4, 0.5e-4, 4e-4, 1e-4], (od_cost.shape[0], 1))
            fixed_cost = np.tile([1e-4, 2e-4, 0.7e-4, 2e-4, 8e-4, 1e-4, 1e-4, 3e-4], (od_cost.shape[0], 1))
            od_cost = pd.DataFrame(fixed_cost, columns=od_cost.columns, index=od_cost.index)

            # fine tuning cost penalties
            if date_format < "20200301":
                port_inst.tau1 = 0.5
            elif date_format > "20200301" and date_format < "20210101":
                port_inst.tau1 = 1.5
            elif date_format >= "20210101":
                port_inst.tau1 = 0.3

            # if date_format > '20210601':
            #     port_inst.tau1 = 0.4

            positions, fexps = self.preds_2_position_with_cost(od_mu, od_cost, B, D, C, sod, port_inst)

            sod = positions.iloc[-1].values.reshape(-1, 1)
            trades = positions.diff(axis=0)
            es_trades = trades.iloc[:, 0].abs().sum()
            print(f"ES trades is: {es_trades}.")

            num_trades = (trades.abs() > 10000).sum(axis=0)
            all_positions.append(positions)
            all_fexps.append(fexps)

        positions_df = pd.concat(all_positions, axis=0)
        fexps_df = pd.concat(all_fexps, axis=0)
        positions_df.columns = self.universe
        port_path = os.path.join(
            self.cfg.output_prefix, self.cfg.system, f"strategy={self.cfg.expr_name}", "portfolio", self.cfg.port_cfg["class"]
        )

        Path(port_path).mkdir(parents=True, exist_ok=True)
        positions_df.to_csv(os.path.join(port_path, f'positions_fexpub{self.cfg.port_cfg["kwargs"]["fexpub"]}.csv'))
        fexps_df.to_csv(os.path.join(port_path, f'fexps_fexpub{self.cfg.port_cfg["kwargs"]["fexpub"]}.csv'))


if __name__ == "__main__":
    fire.Fire(BackTesting)
