"""
Online Simulation and Production
"""
import logging
import os
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import List

from joblib import Parallel, delayed

import numpy as np
import pandas as pd
from tqdm import tqdm

from lib.sft_ym.cds.backtesting.backtesting import resample_bars
from lib.sft_ym.cds.backtesting.config import load_config as load_est_config
from lib.sft_ym.cds.backtesting.utils import extract_hp, init_instance_by_config, make_model_object
from lib.sft_ym.cds.prod.update_calibration import load_hist_preds_rets
from lib.sft_ym.dp.config.config import Config
from lib.sft_ym.dp.config.config import load_config as load_data_config
from lib.sft_ym.dp.dp import (
    add_df_columns,
    calc_previous_bday,
    combine_holidays,
    extract_1_instrument_cc_data78,
    extract_roll_dates,
    front_contract_map,
    get_roll_ratio,
    load_holidays,
    main,
    subsample_all_bar,
)
from lib.sft_ym.dp.dp_fx import main as main_fx
from lib.sft_ym.dp.qesc_dp import load_front_contract
from sft_ym.cds.backtesting.backtesting import BackTesting, resample_bars
from sft_ym.cds.prod.update_calibration import append_adj_factor, one_day_update, str2date
from sft_ym.dp.second_bar import ProcessSecondBar
from lib.sft_ym.cds.prod.audit import emailReport


_logger = logging.getLogger(__name__)
_logger.setLevel(logging.INFO)
formatter = logging.Formatter("%(asctime)s:%(name)s:%(message)s")
stream_handler = logging.StreamHandler()
_logger.addHandler(stream_handler)


def extract_opt_hp_path(hps: List, prediction_path: str, pre_date: str) -> dict:
    ic_grid = {}
    preDate = str2date(pre_date)
    for hp in hps:
        path = BackTesting.add_hp_2_prediction_path(hp, prediction_path)
        upload_path = os.path.join(path, str(preDate.year), str(preDate.month).zfill(2))
        ic_df = pd.read_csv(os.path.join(upload_path, f"{pre_date}_ic.csv"), index_col=0)
        ic_grid[tuple(hp.values())] = ic_df.squeeze()

    opt_hp = max(ic_grid, key=ic_grid.get)
    opt_hp_dict = dict(zip(hp.keys(), opt_hp))
    opt_hp_path_tmp = BackTesting.add_hp_2_prediction_path(opt_hp_dict, prediction_path)
    return opt_hp_path_tmp


def one_day_select(pre_date: str, pre_2date: str, hps: List, prediction_path: str, model_matrices_path: str):
    date = str2date(pre_date)
    pre2date = str2date(pre_2date)

    opt_hp_path_tmp = extract_opt_hp_path(hps, prediction_path, pre_date)
    opt_hp_path = os.path.join(opt_hp_path_tmp, str(date.year), str(date.month).zfill(2))
    opt_hp_path2 = os.path.join(opt_hp_path_tmp, str(pre2date.year), str(pre2date.month).zfill(2))

    _logger.info(f"Extract optimal estimation from {opt_hp_path}.")
    # prediction are generated by yesterday data
    test_data = pd.read_csv(os.path.join(opt_hp_path2, f"{pre_2date}_test_data.csv"), index_col=0)
    opt_pred = pd.read_csv(os.path.join(opt_hp_path2, f"{pre_2date}_preds.csv"), index_col=0)
    opt_coef = pd.read_csv(os.path.join(opt_hp_path, f"{pre_date}_coef.csv"), index_col=0)
    opt_z0 = pd.read_csv(os.path.join(opt_hp_path, f"{pre_date}_z0.csv"), index_col=0)
    opt_M = pd.read_csv(os.path.join(opt_hp_path, f"{pre_date}_M.csv"), index_col=0)
    opt_N = pd.read_csv(os.path.join(opt_hp_path, f"{pre_date}_N.csv"), index_col=0)
    opt_U = pd.read_csv(os.path.join(opt_hp_path, f"{pre_date}_U.csv"), index_col=0)
    opt_Q = pd.read_csv(os.path.join(opt_hp_path, f"{pre_date}_Q.csv"), index_col=0)
    scale = pd.read_csv(os.path.join(opt_hp_path, f"{pre_date}_scale.csv"), index_col=0)

    Path(model_matrices_path).mkdir(parents=True, exist_ok=True)

    opt_coef.to_csv(os.path.join(model_matrices_path, f"{pre_date}.coef.csv"))
    opt_z0.to_csv(os.path.join(model_matrices_path, f"{pre_date}.z0.csv"))
    opt_M.to_csv(os.path.join(model_matrices_path, f"{pre_date}.M.csv"))
    opt_N.to_csv(os.path.join(model_matrices_path, f"{pre_date}.N.csv"))
    opt_U.to_csv(os.path.join(model_matrices_path, f"{pre_date}.U.csv"))
    opt_Q.to_csv(os.path.join(model_matrices_path, f"{pre_date}.Q.csv"))
    scale.to_csv(os.path.join(model_matrices_path, f"{pre_date}.scale.csv"))
    test_data.to_csv(os.path.join(model_matrices_path, f"{pre_2date}.scaled_ret.csv"))
    opt_pred.to_csv(os.path.join(model_matrices_path, f"{pre_2date}.preds.csv"))


def update_model_matrices(
    cfg: Config,
    model_obj: dict,
    y: pd.DataFrame,
    upload_path: str,
    date_format: str,
    scale: pd.DataFrame,
    sym: str,
):
    """
    Update estimation and make overnight return prediction

    Note: since in backtesting we want to simulate estimation without cur_date data
    to make overnight return prediction, we need to use date_format one day later than y.
    """
    date = str2date(date_format)
    upload_path = os.path.join(upload_path, str(date.year), str(date.month).zfill(2))
    Path(upload_path).mkdir(parents=True, exist_ok=True)

    solver = model_obj.fit_train(y)
    M = model_obj.sys.M.todense()
    N = model_obj.sys.N.todense()
    Q = model_obj.sys.Q.todense()
    U = model_obj.sys.U
    coef = model_obj.C
    z0 = model_obj.zhat0

    pd.DataFrame(coef["C1"]).to_csv(os.path.join(upload_path, f"{date_format}_coef.csv"))
    pd.DataFrame(z0).to_csv(os.path.join(upload_path, f"{date_format}_z0.csv"))
    pd.DataFrame(M).to_csv(os.path.join(upload_path, f"{date_format}_M.csv"))
    pd.DataFrame(N).to_csv(os.path.join(upload_path, f"{date_format}_N.csv"))
    pd.DataFrame(Q).to_csv(os.path.join(upload_path, f"{date_format}_Q.csv"))
    pd.DataFrame(U).to_csv(os.path.join(upload_path, f"{date_format}_U.csv"))
    scale.to_csv(os.path.join(upload_path, f"{date_format}_scale.csv"))


def update_pre_pred(
    cfg: Config,
    model_obj: dict,
    train_data: pd.DataFrame,
    test_data: pd.DataFrame,
    upload_path: str,
    date_format: str,
    scale: pd.DataFrame,
    sym: str,
):
    """Update previous day prediction in order to run model selection with new data"""
    date = str2date(date_format)
    _logger.info(f"Running yesterday prediction using model matrices of {str(date)}.")
    upload_path = os.path.join(upload_path, str(date.year), str(date.month).zfill(2))

    preds = model_obj.run_epoch(train_data, test_data)
    preds = pd.Series(preds.ravel(), index=test_data.index)
    final_preds = preds * scale.loc[sym, "std"]

    Path(upload_path).mkdir(parents=True, exist_ok=True)
    pd.DataFrame(final_preds).to_csv(os.path.join(upload_path, f"{date_format}_preds.csv"))
    # prediction date format is shifted since this will be the prediction we make at previous date
    pd.DataFrame(preds).to_csv(os.path.join(upload_path, f"{date_format}_scaled_preds.csv"))
    test_data.to_csv(os.path.join(upload_path, f"{date_format}_test_data.csv"))


class Sim:
    def __init__(self, market: str, date: datetime.date, njobs: int) -> None:
        self.market = market
        self.cur_date = date
        self.njobs = njobs
        self.curDateFormat = self.cur_date.strftime("%Y%m%d")
        self.data_config = f"/home/yu.mu/yuresearch/lib/sft_ym/dp/config/prod/directional_prod_{self.market.lower()}.toml"
        self.est_config = f"/home/yu.mu/yuresearch/lib/sft_ym/cds/prod/config/{self.market.lower()}/direct_prod_dev1_{self.market.lower()}.toml"
        self.log_path = f'/ccny5/dat/strat/sft/yu/cds/log/directional/{self.market}/{self.cur_date.strftime("%Y%m%d")}/'
        self.load_cfg()
        self.system = self.est_cfg.system
        self.universe = self.est_cfg.universe
        self.set_up_log()
        self.setPathDict()

    def set_up_log(self):
        Path(self.log_path).mkdir(parents=True, exist_ok=True)
        file_handler = logging.FileHandler(os.path.join(self.log_path, "daily_update.log"))
        file_handler.setFormatter(formatter)
        _logger.addHandler(file_handler)

    def setPathDict(self):
        "Set dictionary with sym as keys"
        self.matPathDict = {}
        self.preDateDict = {}
        self.preDateFormat = {}
        self.pre2DateDict = {}
        self.pre2DateFormat = {}
        self.matPathDict = {}
        self.predPathDict = {}
        self.adjustedPriceDict = {}
        self.ratioPathDict = {}
        self.cumRatioDict = {}
        for sym in self.universe:
            self.preDateDict[sym] = calc_previous_bday(self.cur_date, sym)
            self.preDateFormat[sym] = self.preDateDict[sym].strftime("%Y%m%d")
            self.pre2DateDict[sym] = calc_previous_bday(self.preDateDict[sym], sym)
            self.pre2DateFormat[sym] = self.pre2DateDict[sym].strftime("%Y%m%d")
            self.matPathDict[sym] = os.path.join(
                self.est_cfg.output_prefix,
                self.est_cfg.system,
                f"strategy={self.est_cfg.expr_name}",
                "model_selection",
                f"{sym}",
                str(self.preDateDict[sym].year),
                str(self.preDateDict[sym].month).zfill(2),
                str(self.preDateDict[sym].day).zfill(2),
            )
            self.predPathDict[sym] = os.path.join(
                self.est_cfg.output_prefix,
                self.est_cfg.system,
                f"strategy={self.est_cfg.expr_name}",
                "prediction",
                f"{sym}",
            )
            prefix = os.path.join(
                self.data_cfg.storage,
                sym,
                self.preDateFormat[sym],
            )
            Path(prefix).mkdir(parents=True, exist_ok=True)
            self.adjustedPriceDict[sym] = os.path.join(
                prefix,
                f"{sym}_{self.preDateFormat[sym]}_adjusted_price.csv",
            )
            self.ratioPathDict[sym] = os.path.join(
                prefix,
                f"{sym}_{self.preDateFormat[sym]}_roll_ratio.csv",
            )
            self.cumRatioDict[sym] = os.path.join(
                prefix,
                f"{sym}_{self.preDateFormat[sym]}_cum_roll_ratio.csv",
            )
        self.minute_price_path = os.path.join(
            self.est_cfg.output_prefix,
            self.est_cfg.system,
            f"strategy={self.est_cfg.expr_name}",
            str(self.cur_date.year),
            str(self.cur_date.month).zfill(2),
        )
        Path(self.minute_price_path).mkdir(parents=True, exist_ok=True)

    def load_cfg(self):
        _logger.info("Load data config.")
        _logger.info("Load estimation config.")
        self.data_cfg = load_data_config(self.data_config)
        self.est_cfg = load_est_config(self.est_config)

    def load_historical_data(self, sym: str):
        path_ = os.path.join(
            self.data_cfg.storage,
            sym,
            self.pre2DateFormat[sym],
            f"{sym}_{self.pre2DateFormat[sym]}_adjusted_price.csv",
        )
        try:
            historical_df = pd.read_csv(path_, index_col=0)
        except Exception:
            raise ValueError(
                f"adjusted price hasn't been generated for {self.pre2DateFormat[sym]} yet."
            )
        historical_df.index = pd.to_datetime(historical_df.index)
        return historical_df

    def load_preDate_df(self, sym: str):
        df = extract_1_instrument_cc_data78(
            sym,
            self.data_cfg.prefix,
            str(self.preDateDict[sym]),
            self.data_cfg.file_name,
            self.data_cfg.field,
            self.data_cfg.timezone,
        )
        df = add_df_columns(df)
        return df

    def extract_front(self, sym: str):
        holidays = combine_holidays(
            load_holidays(self.data_cfg.holiday),
            load_holidays(sym),
        )
        roll_dates = extract_roll_dates(
            self.data_cfg.startdate,
            self.data_cfg.enddate,
            self.data_cfg.lookback,
            sym,
            holidays,
        )
        if self.data_cfg.field == "rth_fx":
            front_contract, second_contract = load_front_contract(sym, self.pre2DateDict[sym])
        else:
            front_map = front_contract_map(
                sym,
                self.data_cfg.startdate,
                self.data_cfg.enddate,
                roll_dates,
            )
            front_contract = front_map.loc[str(self.pre2DateDict[sym]), "FrontContract"]
            second_contract = front_map.loc[str(self.pre2DateDict[sym]), "SecondContract"]
        return front_contract, second_contract

    def extend_subsampled_bars(self, historical_df, front, preDate_df):
        front_df = preDate_df.loc[
            preDate_df["SYMBOL"] == front,
            [
                "LAST_BID",
                "LAST_BID_SIZE",
                "LAST_ASK",
                "LAST_ASK_SIZE",
                "LAST",
                "VOLUME",
                "VWAP",
                "ROOT",
                "EXP",
                "HS",
                "WEIGHTED",
                "MID",
            ],
        ]
        subsampled_bars = subsample_all_bar(front_df, self.data_cfg.freq)
        extended_df = pd.concat([historical_df, subsampled_bars], axis=0)
        return extended_df

    def extend_ratio_df(self, sym: str, front_c: str, sec_c: str, preDate_df: pd.DataFrame):
        ratio_path = os.path.join(
            self.data_cfg.storage,
            sym,
            self.pre2DateFormat[sym],
            f"{sym}_{self.pre2DateFormat[sym]}_roll_ratio.csv",
        )
        ratio_df = pd.read_csv(ratio_path, index_col=0)

        if self.data_cfg.field == 'rth_fx':
            ratio_df.columns = ["FrontContract", "Ratio"]

        # extend ratio and cum ratio
        if front_c == sec_c:
            ratio = 1
        else:
            _logger.info('There is roll adjustment yesterday.')
            ratio = get_roll_ratio(sym, preDate_df, front_c, sec_c, self.data_cfg.field)

        ratio_tmp = pd.DataFrame(
            data=[[front_c, ratio]],
            columns=["FrontContract", "Ratio"],
            index=[str(self.preDateDict[sym])],
        )
        extended_ratio = pd.concat([ratio_df, ratio_tmp], axis=0)
        extended_cum_ratio = extended_ratio.assign(
            Ratio=extended_ratio["Ratio"].iloc[::-1].cumprod().iloc[::-1]
        )
        return extended_ratio, extended_cum_ratio

    def adjust_price(self, extended_df: pd.DataFrame, ratio: float, historical_df: pd.DataFrame):
        price_cols = [
            "LAST",
            "MID",
            "WEIGHTED",
            "HIGH",
            "LOW",
            "OPEN",
            "VWAP",
            "VWAP1",
            "LAST_BID",
            "LAST_ASK",
        ]
        extended_df.loc[historical_df.index, price_cols] = (
            extended_df.loc[historical_df.index, price_cols] * ratio
        )
        return extended_df

    def save_new_data(
        self,
        new_bars: pd.DataFrame,
        new_ratio: pd.DataFrame,
        new_cum_ratio: pd.DataFrame,
        sym: str,
    ):
        _logger.info(f'Saving adjusted price of {sym} for {self.preDateFormat[sym]}.')
        new_bars.to_csv(self.adjustedPriceDict[sym])
        new_ratio.to_csv(self.ratioPathDict[sym])
        new_cum_ratio.to_csv(self.cumRatioDict[sym])

    def append(self):
        """Append daily data at date to the historical data and save the appended data"""
        extended_frame = []
        dfs = []
        adj_factor = []
        for sym in tqdm(self.universe):
            historical_df = self.load_historical_data(sym)
            front_contract, second_contract = self.extract_front(sym)
            preDate_df = self.load_preDate_df(sym)
            new_bars = self.extend_subsampled_bars(historical_df, front_contract, preDate_df)
            new_ratio, new_cum_ratio = self.extend_ratio_df(
                sym, front_contract, second_contract, preDate_df
            )
            new_bars = self.adjust_price(
                new_bars,
                new_ratio.loc[str(self.preDateDict[sym]), "Ratio"],
                historical_df,
            )
            self.save_new_data(new_bars, new_ratio, new_cum_ratio, sym)
            dfs.append(new_bars['WEIGHTED'])
            adj_factor.append(new_ratio["Ratio"])

        minute_price = pd.concat(dfs, axis=1).sort_index()
        adj_factor_df = pd.concat(adj_factor, axis=1)
        minute_price.columns = self.universe
        adj_factor_df.columns = self.universe
        minute_price.index = pd.to_datetime(minute_price.index)
        adj_factor_df = append_adj_factor(adj_factor_df, str(self.cur_date))
        return minute_price, adj_factor_df

    def append_mult_days(self):
        dates = [
            '20241101', '20241104', '20241105', '20241106', '20241107',
            '20241108', '20241111', '20241112', '20241113', '20241114',
            '20241115', '20241118',
        ]
        for date in dates:
            cur_date = datetime.strptime(date, "%Y%m%d").date()
            inst = Sim(self.market, cur_date, self.njobs)
            inst.append()

    def fill_missing(self, minute_price: pd.DataFrame):
        if minute_price.isna().sum(axis=1).any():
            _logger.info("Minute price data contains Nans and ffill missing.")
            minute_price, missing_mask = ProcessSecondBar.fill_missing(minute_price)
        return minute_price

    def subsample_data(self, minute_price: pd.DataFrame):
        minute_rets = np.log(minute_price).diff(axis=0)
        minute_rets.iloc[0, :] = 0

        if self.system == "SISO":
            sub_dict = {}
            for sym in self.universe:
                sub_df = resample_bars(self.est_cfg, minute_rets[sym])
                sub_dict[sym] = sub_df["WEIGHTED"]
            sub_df = pd.DataFrame.from_dict(sub_dict, orient="columns")
            return sub_df
        else:
            raise NotImplementedError

    def one_hp_update(
        self,
        hp: dict,
        sym: str,
        pre_scale: pd.DataFrame,
        scale: pd.DataFrame,
        pre_train_data: pd.DataFrame,
        pre_test_data: pd.DataFrame,
        train_data: pd.DataFrame,
        ic_dates: List,
        metric_obj: object,
    ):
        model_obj = make_model_object(self.est_cfg, hp)
        upload_path = BackTesting.add_hp_2_prediction_path(hp, self.predPathDict[sym])
        update_model_matrices(
            self.est_cfg, model_obj, train_data, upload_path, self.preDateFormat[sym], scale, sym
        )
        update_pre_pred(
            self.est_cfg,
            model_obj,
            pre_train_data,
            pre_test_data,
            upload_path,
            self.preDateFormat[sym],
            pre_scale,
            sym,
        )
        load_hist_preds_rets(upload_path, ic_dates, metric_obj)

    def one_day_update(self, df: pd.DataFrame, sym: str):
        if self.system == "SISO":
            dates = pd.unique(df.index.date)
        else:
            raise NotImplementedError

        assert dates[-1] == self.preDateDict[sym], "last date doesn't match preDate"

        hps = extract_hp(self.est_cfg.hp)
        train_size = self.est_cfg.cv_cfg["kwargs"]["train_size"]
        metric_obj = init_instance_by_config(self.est_cfg.metric_cfg)
        if len(dates) < train_size:
            raise ValueError("Total dates is shorter than window size, the result will be inaccurate.")

        pre_train_dates = dates[:-1]
        pre_test_dates = dates[-1]
        pre_train_data, pre_test_data = (
            df.loc[str(pre_train_dates[0]) : str(pre_train_dates[-1])].copy(),
            df.loc[str(pre_test_dates)].copy(),
        )
        preprocess_obj = init_instance_by_config(self.est_cfg.cv_preprocess_cfg)
        pre_train_data, pre_test_data, pre_scale = preprocess_obj.fit(pre_train_data, pre_test_data)

        # prepare data for training including previous day
        train_dates = dates
        train_data = df.loc[str(train_dates[0]) : str(train_dates[-1])].copy()
        train_data, test_data, scale = preprocess_obj.fit(train_data, None)

        if self.njobs == 1:
            for hp in hps:
                self.one_hp_update(
                    hp,
                    sym,
                    pre_scale,
                    scale,
                    pre_train_data,
                    pre_test_data,
                    train_data,
                    dates[(train_size - 1):],
                    metric_obj,
                )
        else:
            Parallel(n_jobs=self.njobs)(
                delayed(self.one_hp_update)(
                    hp,
                    sym,
                    pre_scale,
                    scale,
                    pre_train_data,
                    pre_test_data,
                    train_data,
                    dates[(train_size - 1):],
                    metric_obj,
                )
                for hp in hps
            )

        one_day_select(
            self.preDateFormat[sym],
            self.pre2DateFormat[sym],
            hps,
            self.predPathDict[sym],
            self.matPathDict[sym],
        )

    def run(self):
        minute_price, adj_factor_df = self.append()
        minute_price = self.fill_missing(minute_price)
        sub_df = self.subsample_data(minute_price)

        for sym in self.universe:
            if self.system == "SISO":
                df = sub_df[[sym]]
            else:
                raise NotImplementedError
            self.one_day_update(df, sym)


if __name__ == '__main__':
    rec_list = ["yu.mu@centivacapital.com"]
    market = sys.argv[1]
    cur_date = datetime.now().date()
    # dates = ['20241101', '20241104', '20241105', '20241106', '20241107',
    #          '20241108', '20241111', '20241112', '20241113', '20241114',
    #          '20241115', '20241118', '20241120', '20241121', '20241122']
    # for date in dates:
    #     cur_date = datetime.strptime(date, '%Y%m%d').date()
    # at current date, we append yesterday to history
    njobs = 1
    inst = Sim(market, cur_date, njobs)
    try:
        tic = time.time()
        inst.run()
        toc = time.time()
        seconds = toc - tic
        subj = f"Update directional signal model matrices successfully for {market} market"
        body = (
            f"Update of directional signal for {market} complete successfully at {str(cur_date)}, "
            f"and it took {seconds:.2f} seconds."
        )
        emailReport(body, subj, rec_list)
    except Exception as e:
        subj = f"Error in directional signal model calibration for {market} market"
        body = (
            f"Update of directional signal for {market} did not complete successfully \n "
            f"{str(type(e))} \n {str(e)}."
        )
        emailReport(body, subj, rec_list)

